CSPharma_TorreControl/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using EntityBasicoDAL.cspharma_informacional;

namespace CSPharma_TorreControl.Pages
{
    public class CreateModel : PageModel
    {
        private readonly EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext _context;

        public CreateModel(EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["CodEstadoDevolucion"] = new SelectList(_context.TdcCatEstadosDevolucionPedidos, "CodEstadoDevolucion", "CodEstadoDevolucion");
        ViewData["CodEstadoEnvio"] = new SelectList(_context.TdcCatEstadosEnvioPedidos, "CodEstadoEnvio", "CodEstadoEnvio");
        ViewData["CodEstadoPago"] = new SelectList(_context.TdcCatEstadosPagoPedidos, "CodEstadoPago", "CodEstadoPago");
        ViewData["CodLinea"] = new SelectList(_context.TdcCatLineasDistribucions, "CodLinea", "CodLinea");
            return Page();
        }

        [BindProperty]
        public TdcTchEstadoPedido TdcTchEstadoPedido { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.TdcTchEstadoPedidos.Add(TdcTchEstadoPedido);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

CSPharma_TorreControl/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EntityBasicoDAL.cspharma_informacional;

namespace CSPharma_TorreControl.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext _context;

        public DeleteModel(EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext context)
        {
            _context = context;
        }

        [BindProperty]
      public TdcTchEstadoPedido TdcTchEstadoPedido { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.TdcTchEstadoPedidos == null)
            {
                return NotFound();
            }

            var tdctchestadopedido = await _context.TdcTchEstadoPedidos.FirstOrDefaultAsync(m => m.CodPedido == id);

            if (tdctchestadopedido == null)
            {
                return NotFound();
            }
            else 
            {
                TdcTchEstadoPedido = tdctchestadopedido;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null || _context.TdcTchEstadoPedidos == null)
            {
                return NotFound();
            }
            var tdctchestadopedido = await _context.TdcTchEstadoPedidos.FindAsync(id);

            if (tdctchestadopedido != null)
            {
                TdcTchEstadoPedido = tdctchestadopedido;
                _context.TdcTchEstadoPedidos.Remove(TdcTchEstadoPedido);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

CSPharma_TorreControl/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EntityBasicoDAL.cspharma_informacional;

namespace CSPharma_TorreControl.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext _context;

        public DetailsModel(EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext context)
        {
            _context = context;
        }

      public TdcTchEstadoPedido TdcTchEstadoPedido { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.TdcTchEstadoPedidos == null)
            {
                return NotFound();
            }

            var tdctchestadopedido = await _context.TdcTchEstadoPedidos.FirstOrDefaultAsync(m => m.CodPedido == id);
            if (tdctchestadopedido == null)
            {
                return NotFound();
            }
            else 
            {
                TdcTchEstadoPedido = tdctchestadopedido;
            }
            return Page();
        }
    }
}

CSPharma_TorreControl/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EntityBasicoDAL.cspharma_informacional;

namespace CSPharma_TorreControl.Pages
{
    public class EditModel : PageModel
    {
        private readonly EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext _context;

        public EditModel(EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext context)
        {
            _context = context;
        }

        [BindProperty]
        public TdcTchEstadoPedido TdcTchEstadoPedido { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.TdcTchEstadoPedidos == null)
            {
                return NotFound();
            }

            var tdctchestadopedido =  await _context.TdcTchEstadoPedidos.FirstOrDefaultAsync(m => m.CodPedido == id);
            if (tdctchestadopedido == null)
            {
                return NotFound();
            }
            TdcTchEstadoPedido = tdctchestadopedido;
           ViewData["CodEstadoDevolucion"] = new SelectList(_context.TdcCatEstadosDevolucionPedidos, "CodEstadoDevolucion", "CodEstadoDevolucion");
           ViewData["CodEstadoEnvio"] = new SelectList(_context.TdcCatEstadosEnvioPedidos, "CodEstadoEnvio", "CodEstadoEnvio");
           ViewData["CodEstadoPago"] = new SelectList(_context.TdcCatEstadosPagoPedidos, "CodEstadoPago", "CodEstadoPago");
           ViewData["CodLinea"] = new SelectList(_context.TdcCatLineasDistribucions, "CodLinea", "CodLinea");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(TdcTchEstadoPedido).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TdcTchEstadoPedidoExists(TdcTchEstadoPedido.CodPedido))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TdcTchEstadoPedidoExists(string id)
        {
          return _context.TdcTchEstadoPedidos.Any(e => e.CodPedido == id);
        }
    }
}

CSPharma_TorreControl/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CSPharma_TorreControl.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CSPharma_TorreControl/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EntityBasicoDAL.cspharma_informacional;

namespace CSPharma_TorreControl.Pages
{
    public class IndexModel : PageModel
    {
        private readonly EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext _context;

        public IndexModel(EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext context)
        {
            _context = context;
        }

        public IList<TdcTchEstadoPedido> TdcTchEstadoPedido { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.TdcTchEstadoPedidos != null)
            {
                TdcTchEstadoPedido = await _context.TdcTchEstadoPedidos
                .Include(t => t.CodEstadoDevolucionNavigation)
                .Include(t => t.CodEstadoEnvioNavigation)
                .Include(t => t.CodEstadoPagoNavigation)
                .Include(t => t.CodLineaNavigation).ToListAsync();
            }
        }
    }
}

CSPharma_TorreControl/Pages/Login.cshtml.cs
using EntityBasicoDAL.cspharma_informacional;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace CSPharma_TorreControl.Pages
{

    public class LoginModel : PageModel
    {
        //CodEmpleado para pasarlo a la vista
        public string CodEmpleado { get; set; }

        //ClaveEmpleado para pasarlo a la vista
        public string ClaveEmpleado { get; set; }

        //Aqui guardamos los mensajes de error y otros avisos, y se los pasamos a la vista.
        [BindProperty]
        public List<string> Mensajes { get; set; }

        private EntityBasicoDAL.cspharma_informacional.CspharmaInformacionalContext context = new CspharmaInformacionalContext();

        public void OnGet()
        {
        }

        //Establecemos metodo OnPostSubmit con variable de la clase de la consulta que queremos realizar
        public void OnPostSubmit(DlkCatAccEmpleado empleado)
        {
            Boolean clave = true;
            Boolean user = true;

            // Comprobacion usuario. Comprobamos que no este vacio, sea nulo o tenga mas de 7 caracteres.
            if ((empleado.CodEmpleado == null) || (empleado.CodEmpleado.Length == 0) || (empleado.CodEmpleado.Length > 7))
            {
                Console.WriteLine("Nombre de usuario no valido.");
                this.Mensajes.Add("Nombre de usuario no valido.");
                user = false;
            }

            // Comprobamos clave. Comprobamos que no este vacia, sea nula o tenga menos de 8 caracteres.
            if ((empleado.ClaveEmpleado == null) || (empleado.ClaveEmpleado.Length == 0) || (empleado.ClaveEmpleado.Length < 8))
            {
                Console.WriteLine("Clave no valida. Tiene que tener al menos 8 caracteres.");
                this.Mensajes.Add("Clave no valida. Tiene que tener al menos 8 caracteres.");
                clave = false;
            }

            
            if(clave && user)
            {
                //Guardamos en una lista la informacion recogida en el contexto
                var usuarios = context.DlkCatAccEmpleados.ToList();

                //Comprobamos que los datos recogidos se corresponden a los datos de un empleado (CodEmpleado y ClaveEmpleado)
                for (int i = 0; i < usuarios.Count; i++)
                {
                    if (usuarios[i].CodEmpleado == empleado.CodEmpleado && usuarios[i].ClaveEmpleado == empleado.ClaveEmpleado)
                    {
                        user = true;
                        break;
                    }
                    else
                    {
                        user = false;
                    }
                }

                //Mensajes de confimacion o negacion de acceso
                if (clave && user)
                {
                    Console.WriteLine("ACCESO CONCEDIDO: Codigo de Empleado y Clave de Empleado correctos.");
                    this.Mensajes.Add("ACCESO CONCEDIDO: Codigo de Empleado y Clave de Empleado correctos.");
                }
                else
                {
                    Console.WriteLine("ACCESO DENEGADO: Codigo de Empleado y Clave de Empleado incorrectos.");
                    this.Mensajes.Add("ACCESO DENEGADO: Codigo de Empleado y Clave de Empleado incorrectos.");
                }
            }         
        }
    }
}

CSPharma_TorreControl/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CSPharma_TorreControl.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CSPharma_TorreControl/Pages/AltaEmpleado.cshtml
@page
<!--Añadimos asistente de etiquetas-->
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
<!--Asignamos el model correspondiente a la clase-->
@model CSPharma_TorreControl.Pages.AltaEmpleadoModel
@{
    ViewData["Title"] = "AltaEmpleado";
}

<div class="container" style="color: #5dc1b9; text-align:center;">

    <form method="post" class="col-xl-3">
        <h3>ALTA EMPLEADO</h3>

        <label for="CodEmpleado" class="form-label">Nuevo Codigo de Empleado:</label>
        <input type="text" class="form-control" name="CodEmpleado" maxlength="7">

        <label for="ClaveEmpleado" class="form-label">Clave de Empleado:</label>
        <input type="password" class="form-control" name="ClaveEmpleado">

        <label for="ConfirmarClave" class="form-label">Confirmar Clave de Empleado:</label>
        <input type="password" class="form-control" name="ConfirmarClave">

        <button type="submit" value="Submit" asp-page-handler="Submit">Dar de Alta</button>

        <br />
        <br />
        <!--Mostramos errores y otros avisos-->
        @if (Model.Mensajes != null)
        {
            <div id="errores">
                <h3>¡¡ATENCIÓN!!</h3>

                @foreach (var mensaje in @Model.Mensajes)
                {
                    <p>@mensaje</p>
                }
            </div>
        }
    </form>
</div>

CSPharma_TorreControl/Pages/Create.cshtml
@page
@model CSPharma_TorreControl.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TdcTchEstadoPedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.CodPedido" class="control-label"></label>
                <input asp-for="TdcTchEstadoPedido.CodPedido" class="form-control" />
                <span asp-validation-for="TdcTchEstadoPedido.CodPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.CodLinea" class="control-label"></label>
                <select asp-for="TdcTchEstadoPedido.CodLinea" class ="form-control" asp-items="ViewBag.CodLinea"></select>
            </div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.MdDate" class="control-label"></label>
                <input asp-for="TdcTchEstadoPedido.MdDate" class="form-control" />
                <span asp-validation-for="TdcTchEstadoPedido.MdDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.MdUuid" class="control-label"></label>
                <input asp-for="TdcTchEstadoPedido.MdUuid" class="form-control" />
                <span asp-validation-for="TdcTchEstadoPedido.MdUuid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.CodEstadoPago" class="control-label"></label>
                <select asp-for="TdcTchEstadoPedido.CodEstadoPago" class ="form-control" asp-items="ViewBag.CodEstadoPago"></select>
            </div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.CodEstadoEnvio" class="control-label"></label>
                <select asp-for="TdcTchEstadoPedido.CodEstadoEnvio" class ="form-control" asp-items="ViewBag.CodEstadoEnvio"></select>
            </div>
            <div class="form-group">
                <label asp-for="TdcTchEstadoPedido.CodEstadoDevolucion" class="control-label"></label>
                <select asp-for="TdcTchEstadoPedido.CodEstadoDevolucion" class ="form-control" asp-items="ViewBag.CodEstadoDevolucion"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CSPharma_TorreControl/Pages/Delete.cshtml
@page
@model CSPharma_TorreControl.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TdcTchEstadoPedido</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.MdDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.MdDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.MdUuid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.MdUuid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodEstadoDevolucionNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodEstadoDevolucionNavigation.CodEstadoDevolucion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodEstadoEnvioNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodEstadoEnvioNavigation.CodEstadoEnvio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodEstadoPagoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodEstadoPagoNavigation.CodEstadoPago)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodLineaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodLineaNavigation.CodLinea)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="TdcTchEstadoPedido.CodPedido" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

CSPharma_TorreControl/Pages/Details.cshtml
@page
@model CSPharma_TorreControl.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TdcTchEstadoPedido</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.MdDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.MdDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.MdUuid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.MdUuid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodEstadoDevolucionNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodEstadoDevolucionNavigation.CodEstadoDevolucion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodEstadoEnvioNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodEstadoEnvioNavigation.CodEstadoEnvio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodEstadoPagoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodEstadoPagoNavigation.CodEstadoPago)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TdcTchEstadoPedido.CodLineaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TdcTchEstadoPedido.CodLineaNavigation.CodLinea)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.TdcTchEstadoPedido?.CodPedido">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

CSPharma_TorreControl/Pages/Index.cshtml
@page
@model CSPharma_TorreControl.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1 style="color: #5dc1b9; text-align: center;">Bienvenido a la Torre de Control de CSPharma</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].MdDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].MdUuid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].CodEstadoDevolucionNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].CodEstadoEnvioNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].CodEstadoPagoNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TdcTchEstadoPedido[0].CodLineaNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.TdcTchEstadoPedido) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MdDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MdUuid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodEstadoDevolucionNavigation.CodEstadoDevolucion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodEstadoEnvioNavigation.CodEstadoEnvio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodEstadoPagoNavigation.CodEstadoPago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodLineaNavigation.CodLinea)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.CodPedido">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.CodPedido">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.CodPedido">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CSPharma_TorreControl/Pages/Login.cshtml
@page
<!--Añadimos asistente de etiquetas-->
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
<!--Asignamos el model correspondiente a la clase-->
@model CSPharma_TorreControl.Pages.LoginModel

@{
    ViewData["Title"] = "Login";
}

<div class="container" style="text-align:center;">


    <!--Establecemos formulario con metodo post para proteger la infromacion en la URL-->
    <form method="post" class="col-xl-3">
        <h3 style="color: #5dc1b9;">
            <font face="Verdana">PAGINA DE REGISTRO</font>
        </h3>

        <label for="CodEmpleado" class="form-label">Codigo de Empleado:</label>
        <input type="text" class="form-control" name="CodEmpleado" maxlength="7">

        <label for="ClaveEmpleado" class="form-label">Clave de Empleado:</label>
        <input type="password" class="form-control" name="ClaveEmpleado">

        <!--Añadimos atributo asp-page-handler complemento de asp-page que genera direcciones URL que envían a cada uno de los métodos de controlador definidos por una página.
            Es decir envia los datos al metodo (en este caso OnPost) que le hemos añadido Submit. 
        -->
        <button type="submit" value="Submit" asp-page-handler="Submit">Enviar</button>
        <br />
        <br />
        <a style="color" asp-area="" asp-page="/AltaEmpleado">Alta Nuevos Empleados</a>

        <br />
        <br />
        <!--Mostramos errores y otros avisos-->
        @if (Model.Mensajes != null)
        {
            <div id="errores" class="col-xl-13">
                <h3>¡¡ATENCIÓN!!</h3>

                @foreach (var mensaje in @Model.Mensajes)
                {
                    <p>@mensaje</p>
                }
            </div>
        }

    </form>
</div>